### ISSUE TITLE
Error on stop with the new version

### ISSUE THREAD

**Issue by Twiz0x** [Electroid/SportPaper#110]
[21:20:14 INFO]: Saving chunks for level 'world'/Overworld
>
at net.craftersland.consolefix.OldEngine$1.stop(OldEngine.java:28)
at org.apache.logging.log4j.core.filter.CompositeFilter.stop(CompositeFilter.java:145)
at org.apache.logging.log4j.core.filter.AbstractFilterable.stop(AbstractFilterable.java:163)
at org.apache.logging.log4j.core.filter.AbstractFilterable.stop(AbstractFilterable.java:150)
at org.apache.logging.log4j.core.config.AbstractConfiguration.stop(AbstractConfiguration.java:315)
at org.apache.logging.log4j.core.LoggerContext.stop(LoggerContext.java:351)
at org.apache.logging.log4j.core.LoggerContext$1.run(LoggerContext.java:279)
at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry$RegisteredCancellable.run(DefaultShutdownCallbackRegistry.java:109)
at org.apache.logging.log4j.core.util.DefaultShutdownCallbackRegistry.run(DefaultShutdownCallbackRegistry.java:74)
at java.lang.Thread.run(Thread.java:748)

**Comment by LewUwU** [comment]
at net.craftersland.consolefix.OldEngine$1.stop(OldEngine.java:28)

Here's your problem
