### ISSUE TITLE
Adding Custom Config

### ISSUE THREAD

**Issue by notcarnage** [Electroid/SportPaper#114]
d

**Comment by LughFPS** [comment]
[00:42:57 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at java.util.Properties$LineReader.readLine(Properties.java:434) ~[?:1.8.0_322]
        at java.util.Properties.load0(Properties.java:353) ~[?:1.8.0_322]
        at java.util.Properties.load(Properties.java:341) ~[?:1.8.0_322]
        at com.minexd.spigot.SpigotXConfig.<init>(SpigotXConfig.java:53) ~[sportpaper-1.8.8-R0.1-SNAPSHOT-remapped.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:185) ~[sportpaper-1.8.8-R0.1-SNAPSHOT-remapped.jar:1.8.8-R0.1-SNAPSHOT]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:667) [sportpaper-1.8.8-R0.1-SNAPSHOT-remapped.jar:1.8.8-R0.1-SNAPSHOT]
        at java.lang.Thread.run(Thread.java:750) [?:1.8.0_322]

**Comment by xIsm4** [comment]
> 
Is a nullPointerexception ,wich means that some config is wrong or you just did not add it.

Btw, why you would backport an otherfork things to this? SportPaper is already great.
