### ISSUE TITLE
Chunk unloading

### ISSUE THREAD

**Issue by SrBlecaute01** [Electroid/SportPaper#119]
Apparently I have this problem when unloading the chunk.

```java
[18:57:35] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_8_R3.ReportedException: Exception ticking world
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:945) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at java.lang.Thread.run(Thread.java:750) [?:1.8.0_332]
Caused by: java.lang.NullPointerException
    at it.unimi.dsi.fastutil.longs.LongOpenHashSet$SetIterator.nextLong(LongOpenHashSet.java:535) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:444) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.WorldServer.doTick(WorldServer.java:236) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:934) ~[Rankup.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
    ... 4 more
```
Seeing the last commits I realized that this error should be fixed by pr #116  or I could be wrong.

[crash-2022-07-30_18.57.35-server.txt](https://github.com/Electroid/SportPaper/files/9228154/crash-2022-07-30_18.57.35-server.txt)

**Comment by Pablete1234** [comment]
I've looked into this a bit, and i'm pretty certain it's related to one of your own plugins, as it's getting into a state it should never get to. Is it possible that any of your plugins handles a ChunkUnloadEvent and does some action that modifies the chunk unload queue in any way (ie: modifying other chunks?)

Regardless, i've not been able to reproduce the issue

**Comment by SrBlecaute01** [comment]
Since it's been a while, I don't think I can reproduce the error again. If I'm not mistaken, I reversed the commit changes and put the default Map used by the paper and the crash stopped happening. I wonder if the error really would be due to modifications.

Also, I don't recall any plugin changing blocks on its offload, just removing entities, but I don't think that should crash the server.
