### ISSUE TITLE
Nether Beds

### ISSUE THREAD

**Issue by zakwanasim** [Electroid/SportPaper#135]
When I right click on beds in the nether, it doesn't work as expected and this is the error
[16:37:01 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:45) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.processTasks(MinecraftServer.java:1726) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.processTasks(DedicatedServer.java:397) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:884) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:365) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:823) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:724) [sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at net.minecraft.server.v1_8_R3.Explosion.a(Explosion.java:163) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.World.createExplosion(World.java:2025) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.WorldServer.createExplosion(WorldServer.java:1059) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.BlockBed.interact(SourceFile:59) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:501) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:805) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) ~[sportpaper-1.8.8-R0.1-SNAPSHOT.jar:git-SportPaper-8de3fda-P.178a2af-SP.28dc63d-CB.e1ebe52]
        ... 7 more

**Comment by HiKingsFR** [comment]
Verified source entity is null (Explosion.java:163)
the issue only occurs when damage is dealt to an entity during the explosion

**Comment by F3F5** [comment]
@Electroid what's new
