### ISSUE TITLE
Problem with "./sportpaper build"

### ISSUE THREAD

**Issue by VerCodeNET** [Electroid/SportPaper#35]
**I have a problem when I want to build a src there is such a error.**

`./sportpaper build
--- Preparing to build SportPaper
--- Setting up build environment
Submodule 'Paper' (https://github.com/PaperMC/Paper.git) registered for path 'base/Paper'
Cloning into '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper'...
Submodule path 'base/Paper': checked out '4c7641d1919222fdf02903bc529af1d6cbbe6146'
Submodule 'BuildData' (https://hub.spigotmc.org/stash/scm/spigot/builddata.git) registered for path 'base/Paper/BuildData'
Submodule 'Bukkit' (https://hub.spigotmc.org/stash/scm/spigot/bukkit.git) registered for path 'base/Paper/Bukkit'
Submodule 'CraftBukkit' (https://hub.spigotmc.org/stash/scm/spigot/craftbukkit.git) registered for path 'base/Paper/CraftBukkit'
Submodule 'Paperclip' (https://github.com/PaperSpigot/Paperclip.git) registered for path 'base/Paper/Paperclip'
Cloning into '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/BuildData'...
Cloning into '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/Bukkit'...
Cloning into '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/CraftBukkit'...
Cloning into '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/Paperclip'...
Submodule path 'base/Paper/BuildData': checked out '838b40587fa7a68a130b75252959bc8a3481d94f'
Submodule path 'base/Paper/Bukkit': checked out '01d1820664a5f881665b84b28871dadd132deaef'
Submodule path 'base/Paper/CraftBukkit': checked out 'e1ebe524a78e27f6a2829ed4574fded3779094e1'
Submodule path 'base/Paper/Paperclip': checked out '1b58efd4de067e40562ba01fefe70cc22a32ffeb'
--- Preparing upstream...
Downloading unmapped vanilla jar...
Applying class mappings...
Exception in thread "main" java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:170)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:436)
        at net.md_5.ss.repo.RuntimeRepo.getClass0(RuntimeRepo.java:25)
        at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
        at net.md_5.ss.repo.AggregateRepo.getClass0(AggregateRepo.java:30)
        at net.md_5.ss.repo.ClassRepo.getClass(ClassRepo.java:22)
        at net.md_5.ss.model.ClassInfo$1.apply(ClassInfo.java:97)
        at net.md_5.ss.model.ClassInfo$1.apply(ClassInfo.java:92)
        at com.google.common.collect.Iterators$8.transform(Iterators.java:799)
        at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:651)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at net.md_5.ss.remapper.EnhancedRemapper.findFieldDeclarer(EnhancedRemapper.java:45)
        at net.md_5.ss.remapper.EnhancedRemapper.mapFieldName(EnhancedRemapper.java:107)
        at net.md_5.ss.remapper.ClassRemapper.visitField(ClassRemapper.java:71)
        at org.objectweb.asm.ClassReader.readField(ClassReader.java:768)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:689)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:506)
        at net.md_5.ss.model.ClassInfo.remap(ClassInfo.java:120)
        at net.md_5.ss.SpecialSource.map(SpecialSource.java:96)
        at net.md_5.ss.SpecialSource.main(SpecialSource.java:44)
Failed to apply class mappings.
scripts/upstream.sh: line 35: cd: PaperSpigot-Server: No such file or directory
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
scripts/importmcdev.sh: line 31: cd: /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/PaperSpigot-Server/: No such file or directory
Initialized empty Git repository in /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/mc-dev/.git/
cp: cannot stat '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/work/1.8.8//net/minecraft/server/*.java': No such file or directory
/bin/ls: cannot access '/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/PaperSpigot-Server/src/main/java/net/minecraft/server': No such file or directory
error: pathspec '.' did not match any file(s) known to git.
scripts/upstream.sh: line 50: cd: PaperSpigot-API: No such file or directory
scripts/upstream.sh: line 50: cd: PaperSpigot-Server: No such file or directory
Deleted tag '1.8.8--2f2122c04575618c76b2f485c1528480c02b5589' (was dde266321)
--- Build environment prepared. Run './sportpaper apply' to apply patches.
--- Applying SportPaper patches
--- Applying SportPaper API patches
scripts/apply.sh: line 22: cd: /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/base/Paper/PaperSpigot-API: No such file or directory
Fetching origin
Initialized empty Git repository in /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/SportPaper-API/.git/
Resetting SportPaper-API to base/Paper...
Switched to a new branch 'master'
fatal: ambiguous argument 'upstream/upstream': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
  Applying patches to SportPaper-API...
Applying: This is SportPaper
error: sha1 information is lacking or useless (pom.xml).
error: could not build fake ancestor
Patch failed at 0001 This is SportPaper
Use 'git am --show-current-patch' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
fatal: previous rebase directory .git/rebase-apply still exists but mbox given.
  Something did not apply cleanly to SportPaper-API.
  Please review above details and finish the apply then
  save the changes with rebuildPatches.sh
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Child module /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/SportPaper-API/pom.xml of /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/pom.xml does not exist @
[ERROR] Child module /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/SportPaper-Server of /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/pom.xml does not exist @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project app.ashcon:sportpaper-parent:1.8-SNAPSHOT (/mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/pom.xml) has 2 errors
[ERROR]     Child module /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/SportPaper-API/pom.xml of /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/pom.xml does not exist
[ERROR]     Child module /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/SportPaper-Server of /mnt/c/Users/majci/WebstormProjects/SportPaper-master/SportPaper/pom.xml does not exist
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException`

**Comment by v404** [comment]
Moj stary mial nowa kobiete i mowil mi ze jest w porzadku ja mowie co ty pierdolisz ta suka cie jebie na kase on wstal stary wstal i mowi co ty kurwa gnoju i lape do mnie wystawia chcial mi liscia wyjebac a ja go na pizde fast attack bomba w oko kurwa na brzuch oddechu nie mogl zlapac sweter mial na sobie na leb mu sweter zalozylem bomby od dolu mu wale na nos wujaszek nas rozdziela ja mialem ta koszule co na dzwikach bylem z guzikami i tak mnie szarpal ze mi wszystkie guziki z koszuil wypadly

**Comment by negative-zer0** [comment]
use brain

**Comment by wajwuz** [comment]
trzy dni bez spania, rozjebana bania. lepiej uzyj glowy i spierdalaj na fiata

**Comment by HappyGFX** [comment]
> use brain

wolę jak robi to ktoś za mnie
