### ISSUE TITLE
Crash + not loading chunks

### ISSUE THREAD

**Issue by andreasdc** [Electroid/SportPaper#87]
[11:22:25] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 2049
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.rehash(LongOpenHashSet.java:607) ~[fastutil-8.4.4.jar:?]
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.add(LongOpenHashSet.java:320) ~[fastutil-8.4.4.jar:?]
	at net.minecraft.server.v1_8_R3.ChunkProviderServer.queueUnload(ChunkProviderServer.java:110) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap$PlayerChunk.b(PlayerChunkMap.java:431) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerChunkMap.removePlayer(PlayerChunkMap.java:206) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerList.disconnect(PlayerList.java:366) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1028) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.handleDisconnection(NetworkManager.java:454) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.NetworkManager.l(NetworkManager.java:466) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.ServerConnection.c(ServerConnection.java:172) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:998) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:410) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:769) ~[spigot.jar:?]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:658) [spigot.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:831) [?:?]

You don't load 0,0 (or spawn?) chunk for 1st person to tp to it and when you quit from there it may cause crash.

**Comment by Electroid** [comment]
Potentially related: #111

**Comment by andreasdc** [comment]
> Potentially related: #111

It was different problem
